# Generated by Django 4.2.5 on 2023-09-13 22:31

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stream_key",
            field=models.CharField(
                default=users.models.generate_stream_key,
                max_length=16,
                unique=True,
                verbose_name="Stream key",
            ),
        ),
    ]
